language: node_js
node_js:
- '12'
before_install: cd client
script:
- npm test
- npm run build
deploy:
  provider: heroku
  app: road-to-discovery
  api_key:
    secure: dd6MnvZpLnoHplKjf5awfV5chOj3L7GMUbzHQ3wa0m79petO2cnZJSOdfIEP1fKkqyjFAnEqN/wJo39LGoIEfhzBU1oS6OkPvrJHKZQsNEn8yU/79oX14BubBVM4cgmHUkNI6U/Yw+zsqD/ISDb5FSd2SVTagtsSJT+Uwu7JW3RWuFaqfYtHvQ1eULZb0EPexXP4iL3udsQ62Ofo7UEPg8bvgTiMdq+t88Id5FULE1YDywyRDQV1HrxNCtFpFby9fzCGETvsA0ulNqBmURIi5BiSadf57RVVSA//sq4pGVbl0v0kXP3+bIbCNgsSTUSVkJBNbJvt/95ICv3ivlKQV+s6SkYpTtJbPEUTmC/GWfvg2d+RuSw31QC6XsSbbQeO/2bZ3HK3txkbLqgJFhT2u9RLFoIvCqcU+DM3iOlrsLGitwwZIBDUbaYbQ01pDqt4dqecCimJoDhzCpl6SMivW8/2p82vscjosMP/VS99wJjXu4OVn6SOQzpdE0++CrC1xrJXGNe8OqYvRwIAxd1KQqkzGkWYTVQ1T3Ym2cLKN2x/CFH2RPTIc3GUgI/lE5EAxkxeO3vju4pF7A1BtRC/zd2gey1PEaUJ5fGfJHMjxuS6/UzgB1KlN9PBmv/F7vWhRD9xfMfAKBDh8ynMv3yp/NPB+iubRxIqLzaO2w7792Q=
