language: node_js
node_js:
- '12'
before_install: cd client
script:
- npm test
- npm run build
deploy:
  provider: heroku
  app: road-to-discovery
  api_key:
    secure: B/+xh7Xsvd4cvCwvp5clOSdoslxg4OI+b0cx7tMcouVUb9BSgcx61HJNqaX0ShTYDxMRTy5T/lsRAaufoV3yjbp4wcebuGwLXplN9Y1QW2xxGeSAG8JdotOqU+oTXGq7tMqpKwfnJlBMrgTe9+pFHj3gaGJss36Xp0CCls12YilbW0i5Z5Biwl7NaahDg8Vs/sXkiEVAY96DJjnVgkIUOKvRNvrP2Y5B/w5ErdgXEWnLKx0G+MqfmbgxHJzghgYu2eZ16yYByxJk5DWqN8lQXcV6frbylpfgBeG7LGVVvZb55nDLtA4LsB0H/dv8I/v6aFhPDCdDaU97Oxq8qzkBFO9dqL5i/8YDzDBHdzpmmtbLCiOTzeXhjMvTRLlAHJNlPTDvAmD41Mt1nJbSDTjdP1bca8ATdezm4Jyv6TGnivYSC54zJpbJaIJSAXAFdb6vUvzCu7JAmYJ3P8fQB9yAFZvImasI91S7+lCez9+Xmgac9Yug7VwHI4tXNuqnxBP038aiMIOOVU44ktFk2CQtTEl7lstr+1GjZicXHorIuKdhjZ9A3QBxY7zQzw9ud6VNeVxmUs0BIZchGkRueG2b70NdQ142ogErYQvbsu0X1DeYnMDW8rKvWCLNRkew+YtbpocXqZ17lqjdVM5rSqq+32YcZMR/xZ26mcenCjsSkiU=
