language: node_js
node_js:
- '12'
before_install: cd client
script:
- npm test
- npm run build
deploy:
  provider: heroku
  app: road-to-discovery
  api_key:
    secure: qp3wANA75aCYOePNrSxagvPsHDyLbzMR8X0m/cfpgxaHDX8LI3LY9nc2hsD0pNzqRYQVvhEP2DV4JNGqLgvgaGElEkixmV1+jR0A8a0ix3Htw34HOmaICVeM16q2W+/FGO6JyfkslrU4ucdSmW9UfmHjWMaVpFLdflXtp+U9uV/XrSH0IMtDkDW7PVMUjJS73yMulRNb5Q37K5v8OLz1rRzP38tQsarYAl8HB577COn6868vWHCyUzhd6vJL0fAGfYOCIhiYi/Buo7J2Ip5xSTJ67q0KkK+HuAfqHvliknsmMhDDzXZ1xOn14x1sRteMfVdd2AifiQI1+fS9IcIpFWnttBbr2i9pqVO4r1seS7WeTvbHAxCNHt5F35A7BaH6D092JtPQ2DXFK1BTxiD6z6JfL4BZyzGgOfoIAddGuFX6APDbZH9V6zCT1C76d3Au//0V0XGc160sHsJYW8y3zAUJXgqHP7neAYOK4jejUKBg+d2/Ap6oPL0onj613xNsjdMHQ4w23SkJBDmfWbz2xdMC7nRdVzy46UQ/mEAuCNx2a96AwA+8qb2nwYxtTYhMatv5sFb+jPIQH85QBLBaf8LXabg6XHOHEAi70Cifiy0SWSxXM56kfrF860lWdf0ntuXV1dGyURoweQ808rAv+Kf+3MogLyksDou6GLsQE0s=
